### PR TITLE
Implement file resource's POSIX inline backend.

### PR DESCRIPTION
**Pull request by pocket7878**
http://serverspec.org/resource_types.html#file

### CODE REVIEW

**Comment by pocket7878** [comment]
Some methods needs platform specific handling. (is_immutable, is_mounted ...etc)

**Comment by mizzy** [comment]
Thanks for your great contribution!

> Should we leave them with default method to return Err?

Yes, please.

**Comment by mizzy** [comment]
Or it is OK leaving them umplemented.

**Comment by pocket7878** [comment]
@mizzy Thank you for your review. I just finished rough implementation.
I wonder if I should leave content_as_{json, yaml} to client-side.

**Comment by mizzy** [comment]
> I wonder if I should leave content_as_{json, yaml} to client-side.

I think so, too.

**Comment by pocket7878** [comment]
Removed contents_as_{json, yaml}.

**Comment by mizzy** [comment]
Thanks a lot!

**Comment by mizzy** [comment]
Released as v0.3.0.

**Pull request merged**
